# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'UniversalApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UniversalApp
  pod 'Masonry', '~> 1.0.2'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'YYKit', '~> 1.0.9'
  pod 'SDWebImage', '~> 4.0.0'

  target 'UniversalAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UniversalAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
